In [1]:
import pandas as pd
import re

df_GSC = pd.read_excel('Excel files\episode GCS.xlsx')
episoodes_GSC = df_GSC['episode'].values
df_GSC

,episode,GCS1,GCS2
0,410,GCS 6/15.Ανισοκορία (ΔΕ). Κατά την παραμ,NaN
1,388,GCS:15/15.Κατα τη διακομιδη του στο ΠΑΓΝ,"GCS:6/15 ΥΤ εγκεφαλου (ΠΑΓΝΗ), αυξηση τω"
2,435,"GCS 13/15 E3V4M6), IΣΟΚΟΡΗ, ΑΥΧΕΝΙΚΗ ΔΥΣ",NaN
3,446,GCS=12/15.Από την ακτινογραφία πρός της,NaN
4,452,"GCS:9/15 (E:3, M:5,V:1) οδηγηθηκε σε επε",NaN
...,...,...,...
1349,5637,"GCS=8/15 (E=2, V=1, M=5) με τελευταία αν",NaN
1350,5639,"GCS 4-5, Sat=50%, ABG : Ph=7.1, PCO2=102",NaN
1351,5640,GCS 15/15 AΨ διαχυτους ΜΜΗ + ΜΗ (κυρίως,NaN
1352,5641,"GCS=11/15 (4-2-5), ήπια ανισοκορία υπέρ",GCS=8/15 με συνοδό εμπύρετο. Ελήφθησαν κ
1353,5644,GCS 14 κατά τη νευρολογική εκτίμηση. Ωστ,NaN

In [2]:
PINAX = pd.read_excel('Excel files\episode-names.xlsx')
episode_PINAX =  PINAX['episode'].values
PINAX['full_name'] = PINAX['LNAME'].str.cat(PINAX['fname'], sep=' ')
PINAX

,episode,HOSPITAL_EPISODE,LNAME,fname,AMKA,note_dt,note,icp,icp_dt,full_name
0,369,2.250271e+09,ΦΑΝΟΥΡΑΚΗΣ,ΑΝΤΩΝΙΟΣ,2.028103e+09,2012-10-15 13:00:00,ΆΞΟΝ ΕΓΚΕΦΑΛΟΥ,17.0,2012-10-15 10:00:00,ΦΑΝΟΥΡΑΚΗΣ ΑΝΤΩΝΙΟΣ
1,369,2.250271e+09,ΦΑΝΟΥΡΑΚΗΣ,ΑΝΤΩΝΙΟΣ,2.028103e+09,2012-10-15 13:00:00,ΆΞΟΝ ΕΓΚΕΦΑΛΟΥ,0.0,2012-10-15 11:00:00,ΦΑΝΟΥΡΑΚΗΣ ΑΝΤΩΝΙΟΣ
2,369,2.250271e+09,ΦΑΝΟΥΡΑΚΗΣ,ΑΝΤΩΝΙΟΣ,2.028103e+09,2012-10-15 13:00:00,ΆΞΟΝ ΕΓΚΕΦΑΛΟΥ,1.0,2012-10-15 12:00:00,ΦΑΝΟΥΡΑΚΗΣ ΑΝΤΩΝΙΟΣ
3,388,2.250273e+09,ΚΑΜΑΡΑΣ,ΑΝΤΩΝΙΟΣ,NaN,2012-10-26 11:30:00,CT ΕΓΚΕΦΑΛΟΥ,13.0,2012-10-26 09:00:00,ΚΑΜΑΡΑΣ ΑΝΤΩΝΙΟΣ
4,388,2.250273e+09,ΚΑΜΑΡΑΣ,ΑΝΤΩΝΙΟΣ,NaN,2012-10-26 11:30:00,CT ΕΓΚΕΦΑΛΟΥ,11.0,2012-10-26 10:00:00,ΚΑΜΑΡΑΣ ΑΝΤΩΝΙΟΣ
...,...,...,...,...,...,...,...,...,...,...
1758,6083,2.250932e+09,ΦΩΤΑ,ΣΟΦΙΑ,2.809450e+10,2023-03-25 08:25:00,ct εγκεφάλου,16.0,2023-03-25 06:29:00,ΦΩΤΑ ΣΟΦΙΑ
1759,6083,2.250932e+09,ΦΩΤΑ,ΣΟΦΙΑ,2.809450e+10,2023-03-25 08:25:00,ct εγκεφάλου,18.0,2023-03-25 06:59:00,ΦΩΤΑ ΣΟΦΙΑ
1760,6083,2.250932e+09,ΦΩΤΑ,ΣΟΦΙΑ,2.809450e+10,2023-03-25 08:25:00,ct εγκεφάλου,28.0,2023-03-25 07:29:00,ΦΩΤΑ ΣΟΦΙΑ
1761,6083,2.250932e+09,ΦΩΤΑ,ΣΟΦΙΑ,2.809450e+10,2023-03-25 08:25:00,ct εγκεφάλου,33.0,2023-03-25 07:59:00,ΦΩΤΑ ΣΟΦΙΑ
1762,6083,2.250932e+09,ΦΩΤΑ,ΣΟΦΙΑ,2.809450e+10,2023-03-25 08:25:00,ct εγκεφάλου,20.0,2023-03-25 08:00:00,ΦΩΤΑ ΣΟΦΙΑ

In [3]:
j=0
COMMON_NAMES =[]
for i in episoodes_GSC:
    if i in episode_PINAX:
        COMMON_NAMES.append((PINAX[PINAX['episode']==i]['full_name'].values[0],i))
        j+=1
print(j)
COMMON_NAMES

201

[('ΚΑΜΑΡΑΣ ΑΝΤΩΝΙΟΣ', 388),
 ('ΤΣΑΓΚΑΡΑΚΗΣ ΓΕΩΡΓΙΟΣ ΑΝΔΡΕΑΣ', 593),
 ('ΧΑΛΚΙΑΔΑΚΗΣ ΑΛΕΞΑΝΔΡΟΣ', 590),
 ('ΑΝΔΡΕΑΔΑΚΗ ΜΑΡΙΑ', 636),
 ('ΜΠΟΡΜΠΟΥΔΑΚΗ ΜΑΡΙΑ', 655),
 ('ΚΕΦΑΛΙΔΗΣ ΚΩΝΣΤΑΝΤΙΝΟΣ', 681),
 ('ΔΑΜΙΑΝΑΚΗΣ ΓΕΩΡΓΙΟΣ', 687),
 ('KANERVA LAURA', 711),
 ('ΑΝΔΡΕΑΔΑΚΗΣ ΒΥΡΩΝ', 713),
 ('ΜΑΡΑΓΚΑΚΗΣ ΓΕΩΡΓΙΟΣ', 717),
 ('ΨΥΚΑΡΑΚΗΣ ΓΕΩΡΓΙΟΣ', 720),
 ('ΚΑΛΙΟΥΝΗΣ ΕΥΑΓΓΕΛΟΣ', 760),
 ('ΧΑΛΑΡΗΣ ΑΝΑΡΓΥΡΟΣ', 777),
 ('ΒΙΔΑΚΗΣ ΚΩΝΣΤΑΝΤΙΝΟΣ', 785),
 ('ΤΡΙΚΟΙΛΗΣ ΙΣΙΔΩΡΟΣ', 814),
 ('ΑΒΕΤΙΣΙΑΝ ΒΑΡΝΤΙΤΕΡ', 856),
 ('KUZIN YURY', 870),
 ('ΔΑΒΡΗΣ ΠΕΤΡΟΣ', 888),
 ('ΣΙΓΑΝΟΥ ΜΑΡΙΑ', 921),
 ('ΚΟΡΟΣΙΔΗΣ ΑΛΕΞΑΝΔΡΟΣ', 938),
 ('ΔΗΜΟΠΟΥΛΟΣ ΓΕΩΡΓΙΟΣ', 956),
 ('ΠΑΠΑΔΑΚΗΣ ΚΩΝΣΤΑΝΤΙΝΟΣ', 984),
 ('ΜΑΚΡΗΣ ΚΩΝΣΤΑΝΤΙΝΟΣ', 993),
 ('KERCIKU FEMI', 1001),
 ('ΤΡΙΠΟΛΙΤΣΙΟΤΗΣ ΕΥΣΤΡΑΤΙΟΣ', 1003),
 ('ΖΙΑΝΑΣ ΤΗΛΕΜΑΧΟΣ', 1021),
 ('ΜΠΑΝΑΝΑ ΓΕΩΡΓΙΑ', 1046),
 ('ΠΡΕΚΑΣ ΙΩΑΝΝΗΣ', 1085),
 ('ΠΕΡΡΑΚΗ ΜΑΡΙΑ', 1128),
 ('ΤΕΡΙΖΑΚΗ ΦΑΝΟΥΡΙΑ', 1157),
 ('ΣΗΦΑΚΗΣ ΓΕΩΡΓΙΟΣ', 1211),
 ('LUNDIE MURIEL', 1215),
 ('ΜΑΡΚΟΥ ΛΑΖΑΡΟΣ', 1254),
 ('ΚΟΥΚΑΚΗ ΕΛΕΝΗ', 1277),
 ('ΚΑΡΤΣΟΓΛΟΥ ΑΝΝΑ', 1318),
 ('ΣΑΡΙΔΟΜΙΧΕΛΑΚΗΣ ΝΙΚΟΛΑΟΣ', 1332),
 ('ΣΦΗΝΙΑΔΑΚΗΣ ΣΤΥΛΙΑΝΟΣ', 1335),
 ('COXHA ARBEN', 1350),
 ('ΔΕΡΜΙΤΖΑΚΗΣ ΕΜΜ', 1377),
 ('ΤΟΨΑΧΑΛΙΔΗΣ ΕΛΕΥΘΕΡΙΟΣ', 1431),
 ('RADOVICH ΕΛΕΝΗ', 1452),
 ('HOXHA KRENAR', 1558),
 ('ΑΣΤΡΟΠΕΚΑΚΗΣ ΓΕΩΡΓΙΟΣ', 1653),
 ('ISUFI ARDJAN', 1668),
 ('ΚΟΥΜΑΝΑΚΟΥ ΜΙΡΑΝΤ', 1735),
 ('AYDI MAHMOOD', 1801),
 ('ΜΑΝΟΥΣΙΔΑΚΗΣ ΕΜΜΑΝΟΥΗΛ', 1807),
 ('ΜΟΥΝΤΡΑΚΗ ΜΑΡΙΑ', 1820),
 ('TRIDENTE GENNARO', 1864),
 ('ΛΕΟΝΤΑΡΑΚΗΣ ΚΩΝ/ΟΣ', 1872),
 ('ΘΥΜΙΑΤΖΗΣ ΜΙΧΑΗΛ', 1937),
 ('ΨΥΧΟΓΙΟΥ ΜΕΡΣΙΝΗ', 1941),
 ('ΚΟΛΙΑ ΣΟΦΙΑ', 1966),
 ('ΜΑΡΤΙΜΙΑΝΑΚΗΣ ΝΙΚΟΛΑΟΣ', 2033),
 ('ΧΟΥΣΤΟΥΛΑΚΗΣ ΓΕΩΡΓΙΟΣ', 2123),
 ('ΣΗΦΑΚΗΣ ΔΗΜΗΤΡΙΟΣ', 2156),
 ('ΦΑΡΣΑΡΗΣ ΝΙΚΟΛΑΟΣ', 2170),
 ('ΚΟΥΚΟΥΖΕΛΗΣ ΝΙΚΟΛΑΟΣ', 2197),
 ('ΣΦΗΝΙΑΣ ΣΤΥΛΙΑΝΟΣ', 2203),
 ('ΚΑΡΤΣΑΚΗΣ ΔΗΜΟΣΘΕΝΗΣ', 2223),
 ('ΔΕΣΠΟΤΑΚΗΣ ΕΜΜΑΝΟΥΗΛ', 2269),
 ('ΜΟΥΛΑΚΑΚΗ ΜΑΡΙΑ', 2295),
 ('BUSCH ANDRIEN', 2324),
 ('MIRKWA HANS GUNTER', 2338),
 ('ΝΟΥΑΡΑΚΗΣ ΙΩΑΝΝΗΣ', 2343),
 ('CIRCEIE VASIL', 2345),
 ('ΛΑΣΘΙΩΤΑΚΗΣ ΣΤΥΛΙΑΝΟΣ', 2351),
 ('ΠΕΡΑΚΗΣ ΓΕΩΡΓΙΟΣ', 2355),
 ('ΜΠΡΙΜΗΣ ΝΙΚΟΛΑΟΣ', 2371),
 ('ΣΑΡΡΗ ΑΙΚΑΤΕΡΙΝΗ', 2382),
 ('PHELPS MARGARET CLARE', 2409),
 ('ΑΡΧΑΒΛΗ ΟΛΓΑ', 2410),
 ('ΣΦΥΡΟΓΙΑΝΝΑΚΗΣ ΓΕΩΡΓΙΟΣ', 2425),
 ('ΠΑΠΑΔΑΚΗΣ ΓΕΩΡΓΙΟΣ', 2430),
 ('HAJDERANJS EMIJLIΑΝ', 2452),
 ('ΔΙΑΛΕΚΤΑΚΗ ΔΗΜΗΤΡΑ', 2472),
 ('ΚΑΡΑΤΖΑ ΑΓΓΕΛΙΚΗ', 2476),
 ('ΚΑΠΑΡΟΥ ΑΝΝΑ', 2477),
 ('ΒΑΣΙΛΑΚΗ ΠΑΡΑΣΚΕΥΗ', 2488),
 ('ΝΟΔΑΡΑΚΗΣ ΣΤΕΦΑΝΟΣ', 2497),
 ('ΠΑΠΑΚΙΡΙΤΣΗΣ ΝΙΚΟΛΑΟΣ', 2563),
 ('ΜΠΕΛΕΦΑΝΤΗΣ ΜΑΡΙΝΟΣ', 2580),
 ('ΠΛΑΙΤΗΣ ΑΝΔΡΕΑΣ', 2631),
 ('ΓΕΩΡΓΑΝΤΑΣ ΚΩΝΣΤΑΝΤΙΝΟΣ', 2656),
 ('ΑΝΔΡΟΥΛΑΚΗ ΜΑΡΙΑ', 2663),
 ('ΣΕΚΕΡΗ ΑΙΚΑΤΕΡΙΝΗ', 2680),
 ('ΤΣΙΚΟΛΙΔΑΚΗΣ ΣΤΕΡΓΙΟΣ', 2711),
 ('ΓΙΑΚΟΥΜΑΚΗΣ ΧΡΗΣΤΟΣ', 2780),
 ('ΚΟΖΑΝΙΔΗΣ ΘΩΜΑΣ', 2784),
 ('ΝΤΑΓΙΑΚΑ ΜΑΡΙΑ', 2824),
 ('ΔΑΝΕΖΗ ΕΥΑΓΓΕΛΙΑ', 2837),
 ('MARIUTSA DMYTRO', 2850),
 ('ΛΙΑΓΚΑΣ ΙΩΑΝΝΗΣ', 2863),
 ('FRAIZER DEBORAH', 2864),
 ('ΜΠΙΝΙΧΑΚΗ ΔΕΣΠΟΙΝΑ', 2884),
 ('ΚΟΥΤΣΑΚΗΣ ΣΤΥΛΙΑΝΟΣ', 2932),
 ('ΔΕΡΜΙΤΖΑΚΗ ΑΙΚΑΤΕΡΙΝΗ', 2955),
 ('ΛΟΥΤΡΑΡΗΣ ΙΩΑΝΝΗΣ', 2972),
 ('ΚΩΣΤΙΔΗΣ ΝΙΚΟΛΑΟΣ', 2975),
 ('ΛΑΔΟΥΚΑΚΗΣ ΝΙΚΟΛΑΟΣ', 2984),
 ('HAUSMANN HARTMUT', 2988),
 ('ΣΤΑΜΑΤΑΚΗΣ ΔΗΜΗΤΡΙΟΣ', 2992),
 ('ΡΟΥΣΕΛΑΚΗ ΖΟΥΜΠΟΥΛΙΑ', 2999),
 ('ΑΡΒΑΝΙΤΗΣ ΑΝΤΩΝΙΟΣ', 3038),
 ('ΧΑΤΖΗΝΙΚΟΛΑΟΥ ΙΩΑΝΝΗΣ', 3050),
 ('ΚΤΕΝΙΑΔΑΚΗΣ ΜΙΧΑΗΛ', 3068),
 ('ΛΑΜΠΡΙΚΙΔΗΣ ΕΛΕΥΘΕΡΙΟΣ', 3069),
 ('FILIPOF DEUTSO', 3076),
 ('WALDSCHOCK ASTRID', 3119),
 ('ΜΑΛΑΔΑΚΗΣ ΜΑΡΙΝΟΣ', 3124),
 ('ΚΑΡΑΓΙΑΝΝΗ ΝΙΚΟΛΙΝΑ', 3125),
 ('ΤΣΑΠΑΚΗΣ ΓΕΩΡΓΙΟΣ', 3126),
 ('ΓΕΩΡΓΑΚΗΣ ΚΩΝΣΤΑΝΤΙΝΟΣ', 3160),
 ('ΡΕΙΖΟΓΛΟΥ-ΚΟΥΤΣΟΜΙΧΑΛΗ ΑΚΡΙΒΗ', 3214),
 ('ΓΚΕΡΕΔΑΚΗΣ ΚΩΝΣΤΑΝΤΙΝΟΣ', 3229),
 ('ΜΠΡΟΤΖΑΚΗΣ ΝΙΚΗΣΤΡΑΤΟΣ', 3252),
 ('ΚΟΛΩΝΗΣ ΓΡΗΓΟΡΙΟΣ-ΑΝΤΩΝΙΟΣ', 3253),
 ('ΤΣΑΓΚΑΡΑΚΗ ΜΑΡΙΑ', 3254),
 ('ΓΑΒΑΛΑΣ ΝΙΚΟΛΑΟΣ', 3259),
 ('ΠΑΠΟΥΤΣΑΚΗ ΜΑΡΙΑ', 3272),
 ('ΤΑΒΕΡΝΑΡΑΚΗΣ ΕΜΜΑΝΟΥΗΛ', 3278),
 ('ALBERTINI LOREDANA', 3294),
 ('STRATICA OVIDIU', 3333),
 ('VON BOETTICHER MARION', 3351),
 ('ΚΑΝΑΚΗΣ ΝΙΚΟΛΑΟΣ', 3425),
 ('ΜΑΡΚΗΣ ΚΩΝΣΤΑΝΤΙΝΟΣ', 3490),
 ('ΒΟΓΙΑΤΖΑΚΗΣ ΝΙΚΟΛΑΟΣ', 3509),
 ('ΚΟΥΡΤΙΚΑΚΗ ΕΥΑΓΓΕΛΙΑ', 3510),
 ('STEIN HORST-PETER', 3590),
 ('ΑΝΑΣΤΑΣΟΥ ΜΙΧΑΗΛ - ΦΙΛΙΠΠΟΣ', 3600),
 ('ΚΑΖΑΚΗ-ΔΑΣΚΑΛΑΚΗ ΕΛΕΝΗ', 3625),
 ('STURITIS TOMS', 3634),
 ('ΓΙΑΚΟΥΜΑΚΗΣ ΕΥΑΓΓΕΛΟΣ', 3640),
 ('ΓΙΑΝΝΑΚΑΚΗΣ  ΑΝΤΩΝΙΟΣ', 3658),
 ('BOGDANOVIC GORAN', 3703),
 ('ΦΩΤΗΣ ΝΙΚΟΛΑΟΣ', 3731),
 ('ΧΛΑΜΙΔΗ ΔΕΣΠΟΙΝΑ', 3747),
 ('ΖΕΡΒΟΥΔΑΚΗΣ ΕΥΑΓΓΕΛΟΣ', 3777),
 ('ΛΟΥΚΑΔΑΚΗΣ ΓΕΩΡΓΙΟΣ', 3801),
 ('ΚΑΤΣΟΥΛΗΣ ΓΕΩΡΓΙΟΣ', 3850),
 ('GOMULA EDYTA ANETA', 3854),
 ('ΠΑΠΑΧΡΗΣΤΟΥ ΕΥΑΓΓΕΛΟΣ', 3856),
 ('FLIPPING SUZAN', 3862),
 ('ΠΑΘΙΑΚΗΣ ΓΕΩΡΓΙΟΣ', 3918),
 ('ΑΒΡΑΜΑΚΗΣ ΓΕΩΡΓΙΟΣ', 3929),
 ('ΖΕΡΒΑΚΗΣ ΕΜΜΑΝΟΥΗΛ', 3974),
 ('ΚΑΡΑΠΙΔΑΚΗΣ ΔΗΜΗΤΡΙΟΣ', 3982),
 ('ΤΣΑΝΤΑΚΗΣ ΝΙΚΟΛΑΟΣ', 4001),
 ('ΤΩΜΑΔΑΚΗΣ ΚΩΝΣΤΑΝΤΙΝΟΣ', 4180),
 ('ΣΚΟΥΛΗΚΑΡΗΣ ΙΩΑΝΝΗΣ', 4188),
 ('ΜΟΥΝΤΡΑΚΗΣ ΝΙΚΟΛΑΟΣ', 4193),
 ('ΒΟΛΑΝΑΚΗΣ ΕΜΜΑΝΟΥΗΛ', 4184),
 ('ΘΕΟΔΩΡΑΚΗΣ ΚΩΝΣΤΑΝΤΙΝΟΣ', 4218),
 ('ΚΟΡΩΝΙΟΣ ΑΡΤΕΜΙΟΣ', 4250),
 ('ΑΝΤΙΣΑ ΜΟΥΣΤΑΦΑ', 4270),
 ('ΚΤΙΣΤΑΚΗΣ ΝΙΚΟΛΑΟΣ', 4287),
 ('ΚΑΡΥΔΗΣ ΜΙΧΑΗΛ-ΠΑΝΤΕΛΗΣ', 4288),
 ('ΤΣΑΓΚΑΡΑΚΗΣ ΦΩΤΙΟΣ', 4303),
 ('ΤΕΖΑΡΗ ΑΡΓΥΡΩ', 4325),
 ('GRAF ELENA', 4384),
 ('ΣΤΡΑΤΑΚΗΣ ΓΕΩΡΓΙΟΣ', 4418),
 ('VASSILEBA VASSILKA', 4449),
 ('ΣΤΡΑΤΑΚΗΣ ΝΙΚΟΛΑΟΣ', 4673),
 ('ΠΑΝΤΕΡΗΣ ΕΜΜΑΝΟΥΗΛ', 4676),
 ('ΝΙΚΟΛΑΙΔΗΣ ΓΕΩΡΓΙΟΣ', 4734),
 ('ΓΡΥΛΛΟΣ ΕΛΕΥΘΕΡΙΟΣ', 4772),
 ('VILAN HASAN', 4814),
 ('ΚΟΚΚΙΝΗΣ ΕΜΜΑΝΟΥΗΛ', 4825),
 ('TAY LOR VOHN VAMES', 4899),
 ('KORJUS MARTIN', 4905),
 ('ΘΕΟΔΟΣΑΚΗΣ ΙΩΣΗΦ', 4917),
 ('ΑΥΓΟΥΛΑΔΑΚΗΣ ΠΑΝΑΓΙΩΤΗΣ', 4965),
 ('ΝΑΤΣΙΟΥΛΑΣ ΝΙΚΟΛΑΟΣ', 5012),
 ('ΚΡΗΤΙΚΟΣ ΚΩΝΣΤΑΝΤΙΝΟΣ', 5027),
 ('ΛΟΥΜΠΑΚΗΣ ΕΜΜΑΝΟΥΗΛ', 5061),
 ('ΛΙΑΚΟΣ ΙΩΑΝΝΗΣ', 5075),
 ('ΑΠΙΔΙΑΝΑΚΗΣ ΚΩΝΣΤΑΝΤΙΝΟΣ', 5074),
 ('ΣΑΚΑΔΑΚΗΣ ΑΝΤΩΝΙΟΣ', 5086),
 ('ΣΗΦΑΚΗ ΑΡΕΤΗ', 5109),
 ('ΨΥΧΑΛΑΚΗΣ ΝΙΚΟΛΑΟΣ', 5179),
 ('ΖΑΡΚΑΔΑ ΖΑΧΑΡΟΥΛΑ', 5220),
 ('ΜΑΡΑΚΗΣ ΘΩΜΑΣ', 5269),
 ('ΓΙΑΧΝΑΚΗ ΜΑΡΘΑ', 5276),
 ('ΠΑΓΙΑΥΛΑΣ ΝΙΚΟΛΑΟΣ', 5283),
 ('ΜΠΑΓΚΕΡΗ ΜΑΡΙΑ', 5317),
 ('ΣΦΑΚΙΑΝΑΚΗΣ ΔΗΜΗΤΡΙΟΣ', 5332),
 ('HIDA ARIOL', 5339),
 ('ΛΑΒΔΑΚΗ-ΣΦΥΡΑΚΗ ΜΑΡΙΝΑ', 5368),
 ('ΤΖΟΥΡΑΣ ΒΑΣΙΛΕΙΟΣ', 5378),
 ('ΚΑΛΑΙΤΖΑΚΗΣ ΣΤΥΛΙΑΝΟΣ', 5432),
 ('KUBIKOVA ANNA', 5454),
 ('ΞΑΝΘΟΠΟΥΛΟΣ ΕΜΜΑΝΟΥΗΛ', 5474),
 ('ΠΑΠΑΔΑΚΗ ΚΑΛΛΙΟΠΗ', 5477),
 ('ΑΚΑΜΩΤΑΚΗΣ ΕΜΜΑΝΟΥΗΛ', 5492),
 ('ΜΑΣΤΟΡΑΚΟΣ ΕΜΜΑΝΟΥΗΛ', 5512),
 ('ΤΣΙΧΛΗΣ ΕΥΑΓΓΕΛΟΣ', 5517),
 ('CAKIROGLU RUHI', 5531),
 ('ΠΑΠΑΔΑΚΗΣ ΔΗΜΗΤΡΙΟΣ', 5569),
 ('HOWANSKI SARAH ELIZABETH ', 5572),
 ('ΜΠΟΡΜΠΑΝΤΩΝΑΚΗΣ ΣΤΕΦΑΝΟΣ', 5573),
 ('HARBORD HANS KIM GRAYDON', 5644)]

In [4]:
df_COMMON_NAMES =pd.DataFrame(COMMON_NAMES, columns=['Name', 'episode'])
df_COMMON_NAMES

                             Name  episode
0                ΚΑΜΑΡΑΣ ΑΝΤΩΝΙΟΣ      388
1    ΤΣΑΓΚΑΡΑΚΗΣ ΓΕΩΡΓΙΟΣ ΑΝΔΡΕΑΣ      593
2          ΧΑΛΚΙΑΔΑΚΗΣ ΑΛΕΞΑΝΔΡΟΣ      590
3                ΑΝΔΡΕΑΔΑΚΗ ΜΑΡΙΑ      636
4              ΜΠΟΡΜΠΟΥΔΑΚΗ ΜΑΡΙΑ      655
..                            ...      ...
196                CAKIROGLU RUHI     5531
197           ΠΑΠΑΔΑΚΗΣ ΔΗΜΗΤΡΙΟΣ     5569
198     HOWANSKI SARAH ELIZABETH      5572
199      ΜΠΟΡΜΠΑΝΤΩΝΑΚΗΣ ΣΤΕΦΑΝΟΣ     5573
200      HARBORD HANS KIM GRAYDON     5644

[201 rows x 2 columns]

In [5]:
# Merging the two DataFrames
GCS_WITH_NAMES = pd.merge(df_GSC, df_COMMON_NAMES, on='episode')
GCS_WITH_NAMES.to_excel("Excel files/GCS_WITH_NAMES.xlsx", index=False)
GCS_WITH_NAMES

,episode,GCS1,GCS2,Name
0,388,GCS:15/15.Κατα τη διακομιδη του στο ΠΑΓΝ,"GCS:6/15 ΥΤ εγκεφαλου (ΠΑΓΝΗ), αυξηση τω",ΚΑΜΑΡΑΣ ΑΝΤΩΝΙΟΣ
1,593,"GCS 5/15. Υπεβλήθη σε CT εγκεγάλου, θώρ",NaN,ΤΣΑΓΚΑΡΑΚΗΣ ΓΕΩΡΓΙΟΣ ΑΝΔΡΕΑΣ
2,590,GCS προ της διασωληνωσης 9-10/15. Εφερε,NaN,ΧΑΛΚΙΑΔΑΚΗΣ ΑΛΕΞΑΝΔΡΟΣ
3,636,GCS 3-4/15 αφού βρισκόταν στο αξονικό γι,NaN,ΑΝΔΡΕΑΔΑΚΗ ΜΑΡΙΑ
4,655,GCS 12/15 (E4M3V4). Αποφασιστηκε η διασω,NaN,ΜΠΟΡΜΠΟΥΔΑΚΗ ΜΑΡΙΑ
...,...,...,...,...
196,5531,GCS 4/15 και στάση απεγκεφαλισμού έγινε,NaN,CAKIROGLU RUHI
197,5569,"GCS 8/15. Διασωληνώθηκε, τέθηκε υπό κατα","GCS 4/15, τετρακινητικός, ανισοκορία υπέ",ΠΑΠΑΔΑΚΗΣ ΔΗΜΗΤΡΙΟΣ
198,5572,GCS με την οποία διασωληνώθηκε η ασθενής,NaN,HOWANSKI SARAH ELIZABETH
199,5573,"GCS 4, E=1 V=1 M=2) και ανισόκορος υπέρ",NaN,ΜΠΟΡΜΠΑΝΤΩΝΑΚΗΣ ΣΤΕΦΑΝΟΣ
200,5644,GCS 14 κατά τη νευρολογική εκτίμηση. Ωστ,NaN,HARBORD HANS KIM GRAYDON

In [6]:
Glasgow_values_whole_line = GCS_WITH_NAMES['GCS1'].values
pattern = r"(\d+)[/=](\d+)"

Glasgow_first_digit = []
line =2
unmatched = []
for text in Glasgow_values_whole_line:
    match = re.search(pattern, text)
    if match:
        Glasgow_first_digit.append( match.groups()[0])
    else:
        unmatched.append((line,text))
    line +=1

print(len(unmatched))
unmatched

48

[(8, 'GCS 3,ισόκορος με μύση.Διασωληνώθηκε και'),
 (18, 'GCS=7(E=4 , V=1 , M=2) όπου και διασωλην'),
 (28, 'GCS προ διασωλήνωσης. Αναφέρεται επεισόδ'),
 (30, 'GCS:8 οποτε και τελεστηκε CT εγκεφαλου π'),
 (31, 'GCS: 9, ισοκορη,αιμοδυναμικα ασταθης, με'),
 (36, 'GCS=13 )μετα απο αιφνιδια δυνατη κεφαλαλ'),
 (43, 'GCS  7-9 (Ε 1-3 V 1 M 5) λόγω ΚΕΚ. Εγινε'),
 (46, 'GCS:9 (Ε:1 V:3-4 M:5) σε έντονη διέγερση'),
 (51, 'GCS=3 κόρες μυδριασμένες χωρίς αντίδραση'),
 (57, 'GCS 8-9).  Ζητήθηκε νέα CT εγκεφάλου που'),
 (59, 'GCS 12-13, διεγερτικός  με 4-5 επεισόδια'),
 (62, 'GCS 14 (E4V4M6) αρνούνταν βοήθεια με απο'),
 (70, 'GCS : 7 (2-1-4) διασωληνώθηκε και τέθηκε'),
 (73, 'GCS=10), εξαιτίας της οποίας και κατοπιν'),
 (77, 'GCS κατά την άφιξη της 7.  CXR εικόνα συ'),
 (84, 'GCS 10 (E3M6V1) '),
 (96, 'GCS 7-8, όπου διασωληνώθηκε και μεταφέρθ'),
 (102, 'GCS= 7 (E:1, V:1 M:5)Διασωλήνωθηκε στο Τ'),
 (107, 'GCS:7, E:1, V:1- Εντοπισμός στον πόνο αρ'),
 (109, 'GCS 4 (απεγκεφαλισμός ΔΕ, παθολογική κάμ'),
 (116, 'GCS 13, θλαστικό αστεροειδές ινιακά (καθ'),
 (124, 'GCS 6 και έγινε total body CT η οποία αν'),
 (126, 'GCS:15 και ήταν τετρακινητικός χωρίς κιν'),
 (127, 'GCS=7 οπότε και διασωληνώθηκε. Στη συνέχ'),
 (133, 'GCS 7-8, κόρες ισομεγέθεις, αντιδρώσες σ'),
 (136, 'GCS:6 (E1, M4, V1). Πριν τη διασωλήνωση '),
 (139, 'GCS περίπου 8, ισόκορος σε μύση, με δεξι'),
 (142, 'GCS 14 (δεν αναφέρουν επιμέρους στοιχεία'),
 (143, 'GCS  E2 M5 V1 = 8), εκτιμήθηκε εκ νέου α'),
 (145, 'GCS 9 (Μ:6, E:2, V:1), και μόλις υποσημα'),
 (150, 'GCS: 9). Mετά τη διασωλήνωση έλαβε δεξαμ'),
 (157, 'GCS:5.  Nέα απεικόνιση ανέδειξε εκτεταμέ'),
 (158, 'GCS:9, κόρες ισομεγέθεις μέσου μεγέθους '),
 (160, 'GCS  6-7 και διασωληνώθηκε.   Ν/χ εκτίμη'),
 (164, 'GCS 6 (E=1, V=1, M=4), ανισόκορος υπέρ Δ'),
 (169, 'GCS:3 και αναφερόμενη απόπνοια αλκοόλ όπ'),
 (170, 'GCS=12. Ο ασθενής ήταν ισόκορος, υπνηλικ'),
 (171, 'GCS 12, σε αυτόμαστη αναπνοή σε μάσκα μη'),
 (177, 'GCS6). Ακολούθησε επείγουσα αξονική τομο'),
 (184, 'GCS 10 κατά την κλινική εξέταση (3-1-6).'),
 (186, 'GCS 14, δεξιά ημιπάρεση, ήπια αταξική συ'),
 (188, 'GCS 3 ισόκορος με φυσιολογικό φωτοκινητι'),
 (190, 'GCS 12, Δεξιά ημιπληγία, αφασία εκπομπής'),
 (194, 'GCS 5 (E=1, V=2, M=2), ανισοκορία υπέρ δ'),
 (197, 'GCS 9 (E 2, V 2, M 5)  και ανισοκορία υπ'),
 (200, 'GCS με την οποία διασωληνώθηκε η ασθενής'),
 (201, 'GCS 4, E=1 V=1 M=2) και ανισόκορος υπέρ '),
 (202, 'GCS 14 κατά τη νευρολογική εκτίμηση. Ωστ')]

In [7]:
with open('unmatched.txt', 'w') as f:  # Changed 'unmatched.text' to 'unmatched.txt'
    for line_number, line_text in unmatched:
        f.write(f"Line {line_number}: {line_text}\n")

In [7]:
from TRANSLATION import greek_to_english

df_GSC_colored = pd.read_excel('Excel files\GCS_WITH_NAMES_colored2.xlsx')


Glasgow_values_whole_line_colored = df_GSC_colored['GCS1'].values
pattern = r"(\d+)[/=](\d+)"

Glasgow_first_digit = []
line =2
unmatched = []
for text in Glasgow_values_whole_line_colored:
    match = re.search(pattern, text)
    if match:
        Glasgow_first_digit.append( match.groups()[0])
    else:
        unmatched.append((line,text))
    line +=1

print(len(unmatched))
print(unmatched)

Glasgow_first_digit_dataframe = pd.DataFrame({'Glasgow_first_digit': Glasgow_first_digit})

GCS_WITH_NAMES_FINAL = pd.concat((Glasgow_first_digit_dataframe, df_GSC_colored),axis=1)
GCS_WITH_NAMES_FINAL = GCS_WITH_NAMES_FINAL.drop('GCS2', axis=1)
GCS_WITH_NAMES_FINAL['NAMES_engl'] = GCS_WITH_NAMES_FINAL['Name'].apply(greek_to_english)
# GCS_WITH_NAMES_FINAL.to_excel("Excel files/GCS_WITH_NAMES_FINAL.xlsx", index=False)
GCS_WITH_NAMES_FINAL

0
[]

,Glasgow_first_digit,episode,GCS1,Name,NAMES_engl
0,15,388,GCS:15/15.Κατα τη διακομιδη του στο ΠΑΓΝ,ΚΑΜΑΡΑΣ ΑΝΤΩΝΙΟΣ,KAMARAS
1,5,593,"GCS 5/15. Υπεβλήθη σε CT εγκεγάλου, θώρ",ΤΣΑΓΚΑΡΑΚΗΣ ΓΕΩΡΓΙΟΣ ΑΝΔΡΕΑΣ,TSAGKARAKIS
2,10,590,GCS προ της διασωληνωσης 9-10/15. Εφερε,ΧΑΛΚΙΑΔΑΚΗΣ ΑΛΕΞΑΝΔΡΟΣ,CHALKIADAKIS
3,4,636,GCS 3-4/15 αφού βρισκόταν στο αξονικό γι,ΑΝΔΡΕΑΔΑΚΗ ΜΑΡΙΑ,ANDREADAKI
4,12,655,GCS 12/15 (E4M3V4). Αποφασιστηκε η διασω,ΜΠΟΡΜΠΟΥΔΑΚΗ ΜΑΡΙΑ,MPORMPOUDAKI
...,...,...,...,...,...
196,4,5531,GCS 4/15 και στάση απεγκεφαλισμού έγινε,CAKIROGLU RUHI,CAKIROGLU
197,8,5569,"GCS 8/15. Διασωληνώθηκε, τέθηκε υπό κατα",ΠΑΠΑΔΑΚΗΣ ΔΗΜΗΤΡΙΟΣ,PAPADAKIS
198,300,5572,??????? GCS 300/15 με την οποία διασωληνώθηκε ...,HOWANSKI SARAH ELIZABETH,HOWANSKI
199,4,5573,"GCS 4/15, E=1 V=1 M=2) και ανισόκορος υπέρ",ΜΠΟΡΜΠΑΝΤΩΝΑΚΗΣ ΣΤΕΦΑΝΟΣ,MPORMPANTONAKIS
200,14,5644,GCS 14/15 κατά τη νευρολογική εκτίμηση. Ωστ,HARBORD HANS KIM GRAYDON,HARBORD

In [8]:
import Levenshtein
import os

def find_similar_strings(target, string_list, threshold):
    similar_strings = []
    for string in string_list:
        distance = Levenshtein.distance(target, string)
        similarity_ratio = 1 - (distance / max(len(target), len(string)))
        if similarity_ratio >= threshold:
            similar_strings.append((string, similarity_ratio))
    return similar_strings 


PATH_TO_PATIENTS = r'C:\Users\user1\Desktop\PAGNI_TEST'
Glasgow_PATIENTS = GCS_WITH_NAMES_FINAL['NAMES_engl'].values
CORRESPOND_PATIENTS = []
counter =0
for patient in os.listdir(PATH_TO_PATIENTS):
    name = patient.split("_")[0]
    similar = find_similar_strings(name,Glasgow_PATIENTS,0.7)
    if similar!=[]:
        print("in PAGNI_TEST -->>",name ,"in GCS_WITH_NAMES_FINAL -->>",similar[0][0],"GCS :",  int( GCS_WITH_NAMES_FINAL[GCS_WITH_NAMES_FINAL['NAMES_engl']==similar[0][0]]['Glasgow_first_digit'].values[0]) )
        counter +=1

print(counter)

in PAGNI_TEST -->> ANDREADAKI in GCS_WITH_NAMES_FINAL -->> ANDREADAKI GCS : 4
in PAGNI_TEST -->> BELEFANTIS in GCS_WITH_NAMES_FINAL -->> MPELEFANTIS GCS : 9
in PAGNI_TEST -->> BORBOUDAKI in GCS_WITH_NAMES_FINAL -->> ZERBOUDAKIS GCS : 8
in PAGNI_TEST -->> DERMITZAKIS in GCS_WITH_NAMES_FINAL -->> DERMITZAKIS GCS : 7
in PAGNI_TEST -->> GEORGAKIS in GCS_WITH_NAMES_FINAL -->> GEORGANTAS GCS : 3
in PAGNI_TEST -->> HAUSMANN in GCS_WITH_NAMES_FINAL -->> HAUSMANN GCS : 7
in PAGNI_TEST -->> HOXHA in GCS_WITH_NAMES_FINAL -->> COXHA GCS : 8
in PAGNI_TEST -->> KALLIOUNIS in GCS_WITH_NAMES_FINAL -->> KALIOUNIS GCS : 4
in PAGNI_TEST -->> KAPAROU in GCS_WITH_NAMES_FINAL -->> KAPAROU GCS : 5
in PAGNI_TEST -->> KARTSOGLOU in GCS_WITH_NAMES_FINAL -->> KARTSOGLOU GCS : 13
in PAGNI_TEST -->> KLINIS in GCS_WITH_NAMES_FINAL -->> KOLONIS GCS : 13
in PAGNI_TEST -->> KOSMADAKIS in GCS_WITH_NAMES_FINAL -->> LOUKADAKIS GCS : 9
in PAGNI_TEST -->> KOUKOUZELIS in GCS_WITH_NAMES_FINAL -->> KOUKOUZELIS GCS : 13
in PAGNI_TEST -->> MARKOU in GCS_WITH_NAMES_FINAL -->> MARKOU GCS : 9
in PAGNI_TEST -->> NODARAKIS in GCS_WITH_NAMES_FINAL -->> NOUARAKIS GCS : 12
in PAGNI_TEST -->> PERAKIS in GCS_WITH_NAMES_FINAL -->> PERRAKI GCS : 8
in PAGNI_TEST -->> SFYROGIANNAKIS in GCS_WITH_NAMES_FINAL -->> SFUROGIANNAKIS GCS : 3
in PAGNI_TEST -->> SIFAKIS in GCS_WITH_NAMES_FINAL -->> BIDAKIS GCS : 3
in PAGNI_TEST -->> STIVAKTAKIS in GCS_WITH_NAMES_FINAL -->> STAMATAKIS GCS : 10
in PAGNI_TEST -->> SYNATSAKIS in GCS_WITH_NAMES_FINAL -->> STRATAKIS GCS : 5
in PAGNI_TEST -->> TERZAKI in GCS_WITH_NAMES_FINAL -->> PERRAKI GCS : 8
in PAGNI_TEST -->> THIMIATZIS in GCS_WITH_NAMES_FINAL -->> THUMIATZIS GCS : 8
in PAGNI_TEST -->> TOPSAXALIDIS in GCS_WITH_NAMES_FINAL -->> TOPSACHALIDIS GCS : 3
in PAGNI_TEST -->> VASILAKI in GCS_WITH_NAMES_FINAL -->> BASILAKI GCS : 15
in PAGNI_TEST -->> XALKIADAKIS in GCS_WITH_NAMES_FINAL -->> CHALKIADAKIS GCS : 10
25